version: "3.8"

services:
    auth_service:
        build:
            context: .
            dockerfile: AuthenticationService/Dockerfile
        volumes:
            - ./AuthenticationService:/usr/src/app
        ports:
            - "8000:8000"
        depends_on:
            - db
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME=authdb
            - DB_USER=admin
            - DB_PASSWORD=adminpassword
        networks:
            - backend

    db:
        image: postgres:13
        environment:
            POSTGRES_DB: authdb
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: adminpassword
        volumes:
            - pgdata:/var/lib/postgresql/data
        networks:
            - backend

    order_service:
        build:
        context: .
        dockerfile: OrderService/Dockerfile
        volumes:
            - ./OrderService:/app
        ports:
            - "5200:5200"         # Expose Order Service on port 5200
        depends_on:
            - matching_engine_service
        environment:
            - MATCHING_ENGINE_URL=http://matching_engine_service:5200/matchOrder
        networks:
            - backend

    matching_engine_service:
        build:
        context: .
        dockerfile: MatchingEngineService/Dockerfile
        volumes:
            - ./MatchingEngineService:/app
        ports:
            - "5300:5300"         # Expose Matching Engine on port 5300
        networks:
            - backend

networks:
    backend:

volumes:
    pgdata:
